### ISSUE TITLE
Get with Git- Website/Shell Edits

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/wiki#102]
Currently in training we are taught to only make edits through pull requests, however there is an easier way that should be introduced at the beginning of the presentation including the distinction of when to use each option (ex: small edits, file upload etc.), each option should explain how they work and contain the examples for practice.

**Comment by jessb0t** [comment]
what a great idea!!!!!!!! <3

**Comment by F-said** [comment]
wow 😮😮😮
