### ISSUE TITLE
New suggestions for the lab Wiki

### ISSUE THREAD

**Issue by kianooshhosseini** [NDCLab/wiki#113]
Hey Everyone, As we will have a section primarily focused on giving an overview of Cognitive control, I suggest that having a similar page(s) for the methods and modalities we use can be valuable. For instance, we can add pages for EEG, computational methods we use, and so on.

I also think of having a new sub-section in the Technical documentation on setting up the BV EEG System, OpenBCI system, and etc. We all can contribute to this sections as we more learn and use these systems. These sections can even include the errors we face, thereby enabling other researchers who face the same difficulties solve their issues rather quickly.

Get with Python: We also can have a page like "Get with Git" for python that helps the lab members learn and begin working with Python quickly. I can contribute to this page. @F-said What do you think? 

In pages related to onboarding, we discuss about the onboarding process and do not provide information on how to  join our lab. I think if we add a line or a paragraph about where we announce new available positions (or how we process new applications through direct contact with the PI), it will help interested applicants to know how to join us.

**Comment by kianooshhosseini** [comment]
@jessb0t, On the Github Templates page, there is a link as a tool development template in the "create a new repo" section. As this template does not exist, I am wondering whether we will have a template for tool development projects? If no, we can delete that line. 
My personal preference is to have a different template for tool development projects.

**Comment by jessb0t** [comment]
@kianooshhosseini Thank you for these thoughts!  Here are my responses:

> Hey Everyone, As we will have a section primarily focused on giving an overview of Cognitive control, I suggest that having a similar page(s) for the methods and modalities we use can be valuable. For instance, we can add pages for EEG, computational methods we use, and so on.

I think this is a wonderful idea.  Would you please create a specific issue for each page you envisage?

> I also think of having a new sub-section in the Technical documentation on setting up the BV EEG System, OpenBCI system, and etc. We all can contribute to this sections as we more learn and use these systems. These sections can even include the errors we face, thereby enabling other researchers who face the same difficulties solve their issues rather quickly.

Agree this will be extremely useful.  Please create the associated issue, create a new branch, and begin recording this information!

> Get with Python: We also can have a page like "Get with Git" for python that helps the lab members learn and begin working with Python quickly. I can contribute to this page. @F-said What do you think?

I will defer to @georgebuzzell and @F-said here.  From my side, this would be a lower priority, but they may disagree.

> In pages related to onboarding, we discuss about the onboarding process and do not provide information on how to join our lab. I think if we add a line or a paragraph about where we announce new available positions (or how we process new applications through direct contact with the PI), it will help interested applicants to know how to join us.

In this particular case, I do not believe this is necessary as this information already lives on our website, which is more "world-facing" than our wiki.  Both are technically open to the public, but the website is "more" public than the wiki, if you will.

> On the Github Templates page, there is a link as a tool development template in the "create a new repo" section. As this template does not exist, I am wondering whether we will have a template for tool development projects? If no, we can delete that line.
My personal preference is to have a different template for tool development projects.

Actually, this template repo already exists (repo name: "template-tool").  It is not 100% complete, but very close.  Before creating a new repo, however, an idea should go through brainBox (also nearing completion!).
