### ISSUE TITLE
Zotero

### ISSUE THREAD

**Issue by kianooshhosseini** [NDCLab/wiki#119]
I assume having a wiki page specifically for Zotero can help the ones who have no idea about Zotero and, in general, reference management software.
I also suggest that we better off give a clear explanation on how rsearchers in the lab should do the literature review and work with the may-review, to-be-reviewed, and reviwed folders as the subfolders of each project correctly. The last part seems to be much more important since it can reduce the confusion and enhance the productivity of our lab.
@jessb0t @georgebuzzell  
As far as I remember, @ostibolt had said that she works on a wiki page for Zotero. Olivia what is your opinion? Can we do that?

**Comment by jessb0t** [comment]
Yes, @kianooshhosseini, @ostibolt was planning to work on this.  Olivia: assigning to you now, but I will let you input the time estimate!

**Comment by jessb0t** [comment]
Completed with #126.
