### ISSUE TITLE
onboarding steps for new RAs

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/wiki#12]
1. intern application
2. Submit an application to CCF-access (Stephanie Aristide)
3. Submit POI request through the online form (George must approve)
4. Follow up with intern to ensure they receive/complete background check forms
2. add to Slack
3. add to Drive
4. CITI training (2 CCF + 1 IRB (only for RAs))
5. HIPAA training (CCF) (follow up with intern to make sure they see/respond to this request from CCF-access)
6. Complete form for RedCap access
7. new user receives and signs data services user agreement
8. Request HPC access
9. Ensure they attend HPC training & follow-up on access being granted
10. Have new member add their contact info
11. Intro to project lead (e.g. Sona, RedCap)

***need to onboard Veronica***
***need to follow-up on all RAs to ensure training complete, background check complete, HPC access granted***

from applicant: application > CITI + photo ID

**Comment by jessb0t** [comment]
@georgebuzzell: I know you already did #1 and #2 for Veronica.  Did you receive the completed application?  Did I miss anything?  I can do #3 and guide her on how to do #4 and #7, but need your guidance on how to trigger #5 and #6 with CCF.

**Comment by georgebuzzell** [comment]
@jessb0t I thought I forwarded the completed app, but maybe not. Will send/resend. There is a second part to the form as well. I will send an example. This all then needs to be sent to Stephanie Aristide (in charge of CCF access.

Thank you for guiding her on (3), (4), and (7). (5) will be automatically triggered via an email from Stephanie to the person being onboarded. Lastly, once the onboarding is complete, I will be sent an email that includes a link to a short redcap form to request redcap access. I can show you this when we next meet?

minor note: In Github, if you include the "#" and then a number, it thinks you are trying to link to those issue numbers for this repo. Instead, do something like "(1)"

**Comment by georgebuzzell** [comment]
@georgebuzzell Sorry! I thought I cc'd you on the email with Veronica's application, etc. but see that is no the case! I just forwarded it all to you. Additionally, I cc'd you on an email to Stephanie to submit Veronica's application and start the FIU/CCF onboarding process. We will also need to submit a POI request; let's go over this when we next meet.

Thank you!!

**Comment by georgebuzzell** [comment]
@jessb0t I made some edits to the steps listed in the issue. Maybe overkill here? Just thought might be helpful for the wiki, but you might have elsewhere already :)

**Comment by jessb0t** [comment]
@georgebuzzell Thank you for the edits and the tip on handling numbers within comments. :)

**Comment by jessb0t** [comment]
@georgebuzzell Added some more to this one so I can organize all current RAs and make sure everything is in order for the current team.  I think I confused you with the above (you put in a confused emoji); I was thanking you for this tip:

> minor note: In Github, if you include the "#" and then a number, it thinks you are trying to link to those issue numbers for this repo. Instead, do something like "(1)"

**Comment by georgebuzzell** [comment]
@jessb0t Apologies! I meant to click the happy face (not the confused/sad face). To make up for it, I added a litany of more positive emojis! :)

**Comment by jessb0t** [comment]
Completed with https://github.com/NDCLab/wiki/pull/30
