### ISSUE TITLE
how-to on HPC access

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/wiki#17]
connect to onboarding info
connect to IPCC training content and schedule
connect to VPN how-to
instructions and screenshots for how to log in
--command line
--GUI

**Comment by jessb0t** [comment]
@F-said Added you to this one so we can divide and conquer (the layman's part and the engineer's part). 🤓

**Comment by F-said** [comment]
working on documenting HPC on [feature-hpc-farukh](https://github.com/NDCLab/wiki/tree/feature-hpc-farukh) as I work getting baseEEG ported to the HPC

**Comment by jessb0t** [comment]
@F-said Awesome!  I'll move to "In Progress" on ZenHub board. :smile:

**Comment by jessb0t** [comment]
Layman's side available on wiki: https://ndclab.github.io/wiki/docs/Onboarding/accessing-hpc.html!

**Comment by F-said** [comment]
I think this one can be marked as resolved since this wiki entry was created (https://ndclab.github.io/wiki/docs/technical-docs/hpc-doc.html). Definitely room for improvement however.

What do you think @jessb0t ?
