### ISSUE TITLE
standards for folder and file naming conventions

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/wiki#25]
Create a wiki page dedicated to standards for file, function, and variable naming conventions

Page should contain the specification of the standards, as well as at least two examples of each. 

This page will be frequently linked to from other wiki pages that mention creation of files, functions, or variable names.

AS WITH ALL WIKI PAGES, IT IS NOT CRUCIAL TO HAVE A "FINAL" VERSION OF THIS PAGE, NOR THE SPECIFICATION/STANDARD ITSELF BEFORE PUBLISHING AND STARTING TO USE THE "WORKING VERSION", then updating as needed. Better to start simple and define what we know is needed, and then add/modify as we go, as opposed to trying to perfect things from the start. Processes and use cases will change, so it is almost impossible for standards to not change over time as well

Initial specification (feel free to suggest additions/edits)

-ALL files, functions, variables ALWAYS start with lower case (even if it is an acronym like "eeg")
-Nouns are separated by "_", compound nouns that are typically two words (e.g., "time slot") are written without a space, and in camelCase (the second word is capitalized)
-files, functions, variables should be human-readable, reflect their content, and uniquely distinguish their content from other variables, functions or files within the same scope. 
-function and variables names should be re-used across programs (but not within programs) to refer to the same kind of thing.
-folder and file names should not ever be re-used. They should always be unique. However, parts of the folder or file name should be re-used as often as possible, with an updated date or appended name to make them unique.
- date format should always be: "2021-03-22" @jessb0t I got this one right, yeah?

**Comment by jessb0t** [comment]
Confirming date format!

**Comment by jessb0t** [comment]
@georgebuzzell
> Nouns are separated by "_", compound nouns that are typically two words (e.g., "time slot") are written without a space, and in camelCase (the second word is capitalized
Thoughts on separating words in file/folder names?  Underscore?

> folder and file names should not ever be re-used. They should always be unique.
This makes total sense to me for file names. But what is the thought process behind unique folder names? For instance, if we create templated folder structures, the top level folder would have a different name but the subfolders would always have the same names in order to assist navigation.

**Comment by georgebuzzell** [comment]
@jessb0t 

> > Nouns are separated by "_", compound nouns that are typically two words (e.g., "time slot") are written without a space, and in camelCase (the second word is capitalized
> 
> Thoughts on separating words in file/folder names? Underscore?

Yes, underscore to separate any words (other than compound nouns). Agree? @jessb0t @F-said 

> 
> > folder and file names should not ever be re-used. They should always be unique.
> 
> This makes total sense to me for file names. But what is the thought process behind unique folder names? For instance, if we create templated folder structures, the top-level folder would have a different name but the subfolders would always have the same names in order to assist navigation.

Ha! Yes, you are right!! folder names should not need to be unique, only file names. Good point! As you state, top-level folder names should be required to be unique, but not necessary for others.

**Comment by georgebuzzell** [comment]
@F-said and @jessb0t Apologies, but I did not realize that pep8 (style standard we have adopted for python) already has standards for naming (silly for me to not check, in hindsight!). Anyways, because we are adopting pep8 for all python code, i think we should exstend this to file/repo/folder, etc names as well, as much as makes sense. thoughts?

https://www.python.org/dev/peps/pep-0008/#naming-conventions

**Comment by jessb0t** [comment]
Adding useful link for git commit message form:
https://chris.beams.io/posts/git-commit/

**Comment by georgebuzzell** [comment]
Excellent, great find @jessb0t !

**Comment by jessb0t** [comment]
@georgebuzzell @F-said 
Any thoughts on why pep8 doesn't call out the possible use of hyphens as word separators?  I've just noticed that I tend to prefer them to underscores.  For instance, in creating new wiki pages, I realize that I've been doing:
**get-with-git.md**
not
**get_with_git.md**
because the underscore requires more keystrokes than the hyphen.

What's funny is that I know I would definitely not use hyphens when naming variables in python or R.  But for file names, the hyphen feels more natural.  I'm certain that I can make myself align to underscores if that's how we decide to go, I'm just wondering if we want to allow both options and make a distinction in usage...?

**Comment by georgebuzzell** [comment]
I'm not sure about pep8 per se. But something called the bids standard that we use for neuro data uses hyphens for things that describe a subcategory and underscore for separate categories:

Sub-01_task-05

I think we want to do something similar here? Honestly the main pep8 standards on naming conventions is pretty unclear. Can you maybe look around to see if other websites may have provided further clarity on usage?

**Comment by jessb0t** [comment]
@georgebuzzell @F-said 

I looked around, but honestly, pep8 is pretty coding-specific.  I think we should use pep8 for Python code, but create our own, reasonable standards for other things, like file/folder names, etc.  I really like the BIDS distinction between hyphen and underscore!

**Comment by jessb0t** [comment]
Removed references to functions and variables, which can be included in #28.

**Comment by georgebuzzell** [comment]
@jessb0t ok great let's follow bids standard as much as possible, but change where needed. Thanks!

**Comment by jessb0t** [comment]
Completed with #71.
