### ISSUE TITLE
establish programming standards

### ISSUE THREAD

**Issue by F-said** [NDCLab/wiki#28]
## Python

- Global variables should not be used

- Leave out return types and parameter types in the function header.
    Example: Do this,
    ```python
    def funcName(a, b):
        ...
    ```
    Not this,
    ```python
    def funcName(a: int, b: int) -> int:
        ...
    ```

- Compartmentalize features into modules. 
    Example: 
    ```python
    import final-reject as fj
    fj.final_reject(raw)
    ```

- Each function should have responsibility for a **single** part of its' module's functionality. Functions that do multiple things should be broken into multiple functions. This ensures reusability & relaxes cognitive load. 
     - If a function is running into >100 lines of code or contains some potentially reusable code, and is not inseparable, further decompose the function into helper functions. 
    Example:
    ```python
    def funcName(a, b):
        # remove extension and other characters for file 
        file_name1 =  "test_file.eeg".lower().replace("-", "").replace("_", "").replace(" ", "")
        file_name1 =  filename[:-4] 

        # do same for other file
        file_name 2=  "test_file_EXTRA.eeg".lower().replace("-", "").replace("_", "").replace(" ", "")
        file_name2 =  filename[:-4] 
    ```

    can be decomposed into

    ```python
    def file_standardize(fn):
        file_name =  fn.lower().replace("-", "").replace("_", "").replace(" ", "")
        return filename[:-4] 

    def funcName(a, b):
        file_name1 =  file_standardize("test_file.eeg")
        file_name2 =  file_standardize("test_file_EXTRA.eeg")
    ```

- Every main feature function should contain docstrings (following [PEP 257](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings)) that follow the format of [MNE functions](https://github.com/mne-tools/mne-python/blob/maint/0.22/mne/io/egi/egi.py#L89-L154) and describe **at most** the following:
    - A brief description as to what the function does.
    - Parameters: which inputs will be provided to the function?
    - ~~Preconditions: what input preconditions should the user of the function abide by to ensure correct behavior.~~
    - ~~Postconditions: what will the function guarantee in its output.~~
    - Throws: which exceptions will the function throw (if any).
    - ~~Modifies: which inputs will be modified (if any).~~
    - Returns: which inputs will be returned, and what changes will be made to them.
    - ~~A small example of how the function should work, if needed.~~
  
        Example:
    ```python
    def add_up(a, b):
        """A function that returns the sum of two inputs 
        Parameters 
        ----------
        a : int
            any integer
        b : in
            any integer

        Postconditions
        ----------
        add_up(a, b) == a + b

        Returns 
        ----------
        a + b
        """
        return a + b
    ```

    This documentation should be as **non-restrictive** as possible. That is, minimize implicit preconditions (don't make assumptions on user input) and maximize implicit postconditions. This will ensure that features are resilient and break correctly and informatively when improper input is provided. 

    Note that if the documentation for any of these categories is empty, it is not required to list it.  For example, a function that returns nothing will likewise have no "returns" listed in the docstring. 

- Follow function, variable, package, and file-naming standards listed in issue #25.

- Every repository should have a succinct `readme.md` that guides development and points to relevant data.

- for [documenting classes](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings): "docstring for a class should summarize its behavior and list the public methods and instance variables. 
    Example:
    ```python
    class Dog(Animal):
        """Dog class that can learn and execute tricks 
        
        Instance Variables
        ----------
        name: str
            the dog's name 
        tricks: list
            a list of strings that contain tricks in string form

        Public Methods
        ----------
        learn_trick(trick)
            method to take in "trick" and store it into tricks list
        
        do_trick()
            method to randomly print out a trick to console
        """
    ```

## Containerization
- Updates to container content should be discrete and announced events. This will prevent unexpected behavior (sudden unsupported packages, changes in kernel) in local environments. 

Borrowed the function documentation standard from previous software engineering courses to help with development. Please let me know if this standard for Python is lacking, or contains too much @yanbin-niu @Jonhas @stevenwtolbert

**Comment by Jonhas** [comment]
@F-said  I would like to add that functions should be written to fit one purpose only. It is best to keep functions as small as possible to assure reusability and ease of testing. This way any side effects or copies can easily be tested through unit testing. With regards to documenting our code, it may be a little redundant. The modification, post conditions, preconditions of an object or primitive variable used as input can be explicitly described within the brief description. Additionally, a small example could be too much to write if the function is complex and if it depends on some other function. I agree with everything else you've mentioned.

**Comment by F-said** [comment]
Incorporated above edit to issue description.

**Comment by F-said** [comment]
added standards for documenting classes

**Comment by F-said** [comment]
added standards for containers

**Comment by yanbin-niu** [comment]
@F-said Everything looks great to me, including the one @Jonhas mentioned.

1. Something might be added into #25 for naming convention:

Naming - always use meaningful descriptive names. 
-  UpperCamelCase for class names (class ImageSprite:);
-  CAPITALIZED_WITH_UNDERSCORES for constants (MAX_PARTICIPANTS = 10)
-   lowercase_separated_by_underscores for other names (variables and methods).

2. Something might be added into commenting besides your perfect example:
Leave author info at the beginning of python file, including original author and authors who modified code (not only for credit, but also for the person that we can turn to), example:

```
# Authors: xxx <xxx@xxx.com> - original Author
#          xxx <xxx@xxx.com> - fix the bug for xxx
```

for authors who modify code should also comment in the place where the modification happens. 
```
# fix the bug for xxx by who
math.floor(a + b)
```

3. Avoid magic numbers.

**Comment by georgebuzzell** [comment]
@F-said @yanbin-niu @Jonhas I really appreciate these really helpful contributions!

I would like to backtrack on my initial suggestions for naming conventions, in places where they disagree with Pep8. Apologies, but I had not realized that Pep8 already has naming convention standards, and I think we should just follow those. Moreover, @F-said and @jessb0t I think we should apply the Pep8 naming conventions beyond just python code, and used for folder/repo names, file names, etc. Thoughts? 

https://www.python.org/dev/peps/pep-0008/#naming-conventions

**Comment by jessb0t** [comment]
@F-said , I have extracted this content and included it in the following two pages on wiki/etiquette-jess

- naming-conventions.md
- programming-conventions.md

**programming-conventions.md**
You'll find several notes from me that start with a long line of dashes.  Let me know if you have any questions about these!  Please feel free to make changes to this file directly on my branch if you'd like as I won't be touching it further.

**naming-conventions.md**
Would you take a look at this page and let me know if there are other things that you think we should add at this point in time?  Feel free to push changes to it on my branch!

Thanks! :)

**Comment by jessb0t** [comment]
Completed with #71.
