### ISSUE TITLE
zenhub defaults research and set up

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/wiki#31]
-Check if possible to create a default zenhub pipeline layout when creating a new workspace

-If so, create defaults and document in lab manager notebook

**Comment by jessb0t** [comment]
No immediate answer on ZenHub docs, contacted support 5/5.

**Comment by jessb0t** [comment]
Support response 5/5:

> Thanks for reaching out. Appreciate the feedback on this. Currently the default pipeline (farthest left) for all new Issues is a global setting for all users in the tool. The ability to set a customized default set of pipelines doesn't exist today. That said, we have received feedback regarding default settings for workspaces and I will make sure to add your feedback so our Product team is aware. I'm sorry that I don't have better news at this time. If you have anything other questions don't hesitate to reach out.

**Comment by georgebuzzell** [comment]
Thanks for checking on this, @jessb0t !
