### ISSUE TITLE
yoke issues to each other across workspaces in zenhub

### ISSUE THREAD

**Issue by georgebuzzell** [NDCLab/wiki#35]
-research how to do this
-set up for at least one issue
-create a short wiki entry describing how to do this

**Comment by jessb0t** [comment]
I believe this is how we create dependencies across repos:
![image.png](https://images.zenhubusercontent.com/6054b276e1e4e5cb58c9e577/69ca4f11-a3c4-438c-b306-d3ca4d6f0731)
