### ISSUE TITLE
ghHowTo-user access levels

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/wiki#41]
We need to determine user access levels in GH so that incoming members are invited at the right level.
- What are the possible kinds of access?  (There is Owner and Member, but there may be subdivisions within these umbrella terms?)
- Which levels do we want to assign to which lab roles?

@F-said and @georgebuzzell : Hoping we can figure these details out in the next week since it plays a role in the GitHub onboarding that I'm working on.  I added to the Aug 1 epic and assigned to you, but will let you estimate time required.  Thanks!

**Comment by georgebuzzell** [comment]
@jessb0t just to add to my last comment. I don't think we will need/want a particular pattern of access tied to particular roles (i.e. j ra, s ra, research tech, etc.). Instead, I think it should be defined as project-specific. However, there may be other nuances I missed, in which case we would want to create an additional team for each role that might layer on additional blanket privileges across repos.

thank you for thinking about this; definitely important!

**Comment by jessb0t** [comment]
Thanks @georgebuzzell .  This makes sense for now, but I'm sure I'll be reaching out with more questions as I try to implement. :)

**Comment by jessb0t** [comment]
Note to self: update brainBox readme with specific instructions for who should be tagged when moving issue to Roasting phase.

**Comment by jessb0t** [comment]
@georgebuzzell @F-said 

I've been doing some research into GitHub permissions.  For reference, [here is an overview of what each access level enables](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization).

A first thought on next steps in terms of access levels:

1. Define lab-wide repos (such as wiki, instruments, etc.).
2. Clean up any remaining non-lab-wide and non-project-specific repos.
3. Create default team for lab-wide repos.  This team consists of all lab members.  It receives Write access on lab-wide repos and Read access on all other lab repos.  Establish admission onto this team as part of lab onboarding process.
2. Create team for each project repo.  Team receives Write access on this specific repo.  Establish admission onto this team as part of project onboarding process.

However, from what I have found so far, push access is global based on having Write access.  That is, if someone has Write access to the repo, **they also have push access to the main branch.**  So we may need a different solution to protect the main branches.  I'm betting you guys already have some other ideas, but here is what I found:
https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

Adding this to our agenda for next week!

**Comment by georgebuzzell** [comment]
This all sounds great, @jessb0t 

One comment: my understanding is that write access and push access are synonymous here, am I wrong?

Also, I originally thought that push (write) had to apply to all branches in a repo, but I believe @F-said said it was possible to limit that. @F-said can you please comment further? Relatedly, suggestions on whether we should implement protections to main by default? And if those protections are in place, how are changes moderated?

**Comment by jessb0t** [comment]
Completed with rollout of project teams within GitHub at release of template repos.
