### ISSUE TITLE
update default to main

### ISSUE THREAD

**Issue by jessb0t** [NDCLab/wiki#46]
Now that we've dropped the gh-pages level, should we update the default to main?

Also, I think we need to update the readme?

@F-said I think this is in your bailiwick. :)  I'll let you estimate the time required!  Thank you!

**Comment by F-said** [comment]
- set default branch to main
- made PR to update readme #52

**Comment by jessb0t** [comment]
Thank you again, @F-said!  Closing issue with completion of merged PR #52.
